---
- name: installation of apache server on {{ deb }} server
  apt: name=apache2 state=installed
  when: ansible_os_family == "{{ deb }}"

- name: installation of httpd server on {{ rh }} server
  yum: name=httpd state=installed
  when: ansible_os_family == "{{ rh }}"

- name: changing the port number for apache
  template: src=ports.conf.j2 dest=/etc/apache2/ports.conf
  notify: restarting apache
  when: ansible_os_family == "{{ deb }}"

- name: changing the port number for httpd
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  notify: restarting httpd
  when: ansible_os_family == "{{ rh }}"

